# Generated by Django 5.1.3 on 2024-11-08 10:52

import apps.user.managers
import apps.user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.user.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=18, unique=True, validators=[apps.user.validators.phone_validator], verbose_name='Phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=None, null=True, upload_to='user_profile_image', verbose_name='Profile photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(default=0, verbose_name='Telegram id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Last name'),
        ),
    ]
