# Generated by Django 5.1.3 on 2024-11-08 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Model id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=128, verbose_name='Product name')),
                ('name_uz', models.CharField(max_length=128, null=True, verbose_name='Product name')),
                ('name_ru', models.CharField(max_length=128, null=True, verbose_name='Product name')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_uz', models.TextField(null=True, verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='product_image', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Model id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('size', models.CharField(choices=[('l', 'Liter'), ('mcub', 'Kub metr'), ('mkv', 'Kvadrat metr'), ('t', 'Tonna'), ('cm', 'Santimetr'), ('g', 'Gramm'), ('kg', 'Kilogramm'), ('port', 'Porsiya'), ('m', 'Metr'), ('pcs', 'Dona')], max_length=28, verbose_name='Size')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.product', verbose_name='Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
