# Generated by Django 5.1.3 on 2024-11-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_product_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='name_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
    ]
