# Generated by Django 5.1.3 on 2024-11-08 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_productsize_name_ru_productsize_name_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_sizes', to='common.product', verbose_name='Product'),
        ),
    ]
