# Generated by Django 5.1.3 on 2024-11-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_productsize_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsize',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
