# Generated by Django 5.1.3 on 2024-11-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cateogry_type',
            new_name='category_type',
        ),
    ]
