# Generated by Django 5.1.3 on 2024-11-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner_image/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='phone_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_image/', verbose_name='Image for phone'),
        ),
    ]
